# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27

install: pip install tox

script: tox

notifications:
  email: false